#!/bin/bash

TRIPLE=aarch64-linux-gnu

aarch64_prefix=/usr/$TRIPLE

PATH=${aarch64_prefix}/bin:$PATH cmake \
    -DCMAKE_INSTALL_PREFIX:PATH=${aarch64_prefix} \
    -DCMAKE_INSTALL_LIBDIR:PATH=lib \
    -DCMAKE_CXX_IMPLICIT_INCLUDE_DIRECTORIES:PATH=${aarch64_prefix}/include \
    -DCMAKE_C_IMPLICIT_INCLUDE_DIRECTORIES:PATH=${aarch64_prefix}/include \
    -DCMAKE_BUILD_TYPE=None \
    -DBUILD_SHARED_LIBS:BOOL=ON \
    -DCMAKE_TOOLCHAIN_FILE=${aarch64_prefix}/toolchain-$TRIPLE.cmake \
    "$@"
    # -DCMAKE_CROSSCOMPILING_EMULATOR=/usr/bin/$TRIPLE-wine \
    # "$@"
