FROM --platform=linux/arm64 ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
  g++ \
  make \
  file \
  curl \
  ca-certificates \
  python3 \
  git \
  sudo \
  libssl-dev \
  pkg-config \
  xz-utils \
  wget \
  clang \
  cmake \
  ninja-build \
  lsb-release software-properties-common gpg \
  && rm -rf /var/lib/apt/lists/*
#  gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu \
#  && rm -rf /var/lib/apt/lists/*

RUN wget https://apt.llvm.org/llvm.sh && chmod u+x llvm.sh && ./llvm.sh 17

# RUN mkdir -p /usr/aarch64-linux-gnu

# RUN wget https://github.com/llvm/llvm-project/releases/download/llvmorg-17.0.6/clang+llvm-17.0.6-aarch64-linux-gnu.tar.xz && \
#     tar -xvf clang+llvm-17.0.6-aarch64-linux-gnu.tar.xz -C /usr/aarch64-linux-gnu && rm clang+llvm-17.0.6-aarch64-linux-gnu.tar.xz

# COPY ./aarch64-linux-gnu-cmake /usr/bin
# COPY ./toolchain-aarch64-linux-gnu.cmake /usr/aarch64-linux-gnu

WORKDIR /build

RUN git clone https://github.com/Vinz2008/C.

WORKDIR /build/C.
    
RUN git submodule update --init --recursive

#RUN CMAKE_GC=TRUE make
# RUN CC="aarch64-linux-gnu-gcc" CXX="aarch64-linux-gnu-g++" TARGET=aarch64-linux-gnu CMAKE=aarch64-linux-gnu-cmake CMAKE_GC=TRUE make

#RUN CC="clang -target aarch64-unknown-linux-gnu" CXX="clang++ -target aarch64-unknown-linux-gnu" make -j$(nproc)