FROM ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
  g++ \
  make \
  file \
  curl \
  ca-certificates \
  python3 \
  git \
  sudo \
  libssl-dev \
  pkg-config \
  xz-utils \
  clang \
  && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /cross-compiled-root

RUN wget https://github.com/llvm/llvm-project/releases/download/llvmorg-17.0.6/clang+llvm-17.0.6-aarch64-linux-gnu.tar.xz && \
    tar -xvf clang+llvm-17.0.6-aarch64-linux-gnu.tar.xz -C /cross-compiled-root && rm clang+llvm-17.0.6-aarch64-linux-gnu.tar.xz


RUN git clone https://github.com/Vinz2008/C.

WORKDIR /build/C.
    
RUN git submodule update --init --recursive

#RUN CC="clang -target aarch64-unknown-linux-gnu" make -j$(nproc)