FROM ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
  g++ \
  make \
  file \
  curl \
  ca-certificates \
  python3 \
  git \
  sudo \
  libssl-dev \
  pkg-config \
  xz-utils \
  wget \
  clang \
  mingw-w64 \
  ninja-build \
  cmake \
  && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /build

WORkDIR /build

COPY ./vars.sh /build

COPY ./download-files.sh /build
RUN ./download-files.sh

COPY ./install-tomlplusplus.sh /build
RUN ./install-tomlplusplus.sh

RUN ls
COPY ./install-cmake-mingw.sh /build
RUN ./install-cmake-mingw.sh

COPY ./build-clang-llvm.sh /build
RUN  ./build-clang-llvm.sh

RUN git clone https://github.com/Vinz2008/C.

WORKDIR /build/C.
    
RUN git submodule update --init --recursive
