# same as rust
FROM centos:7 

WORKDIR /build

RUN yum upgrade -y && \
    yum install -y epel-release && \
    yum install -y \
      bzip2 \
      file \
      gcc \
      gcc-c++ \
      git \
      glibc-devel.i686 \
      glibc-devel.x86_64 \
      libstdc++-devel.i686 \
      libstdc++-devel.x86_64 \
      make \
      pkgconfig \
      python3 \
      unzip \
      wget \
      xz \
      which \
      libtool \
      zlib-devel.i686 \
      zlib-devel.x86_64 \
      && yum clean all

RUN wget https://github.com/llvm/llvm-project/releases/download/llvmorg-17.0.6/clang+llvm-17.0.6-x86_64-linux-gnu-ubuntu-22.04.tar.xz && \
    tar -xvf clang+llvm-17.0.6-x86_64-linux-gnu-ubuntu-22.04.tar.xz -C /usr && rm clang+llvm-17.0.6-x86_64-linux-gnu-ubuntu-22.04.tar.xz


RUN git clone https://github.com/Vinz2008/C.

WORKDIR /build/C.

RUN git submodule update --init --recursive

RUN make -j$(nproc)